name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 실행

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Node.js 설치 및 React 빌드
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies and build React
      working-directory: frontend
      run: |
        npm install
        npm run build

    # 3. Java 설치 및 Spring Boot 빌드
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Spring Boot
      run: |
        ./mvnw clean package

    # 4. EC2에 JAR 파일 배포
    - name: Deploy to EC2
      env:
        REMOTE_HOST: 52.79.138.214        # EC2 퍼블릭 IP
        REMOTE_USER: ubuntu               # EC2 사용자 이름
        KEY_PATH: ${{ secrets.EC2_KEY }}  # GitHub Secrets에 저장된 PEM 키
      run: |
        echo "$KEY_PATH" > private.pem
        chmod 600 private.pem
        scp -i private.pem target/kingsejong-1.0-SNAPSHOT.jar $REMOTE_USER@$REMOTE_HOST:/home/ubuntu/deploy/
        ssh -i private.pem $REMOTE_USER@$REMOTE_HOST "pkill -f java || true && nohup java -jar /home/ubuntu/deploy/kingsejong-1.0-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 &"
