name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 환경 설정: Java, Node.js, Maven 설치
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo apt-get install -y maven

    # 3. React 빌드
    - name: Build React
      run: |
        cd frontend
        npm install
        CI=false npm run build
        mkdir -p ../src/main/resources/static/
        cp -r build/* ../src/main/resources/static/

    # 4. Spring Boot 빌드
    - name: Build Spring Boot
      run: |
        mvn clean package

    # 5. EC2에 JAR 파일 배포 및 실행
    - name: Deploy to EC2
      env:
        REMOTE_HOST: 
