name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup environment
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    # 3. Build React
    - name: Build React
      run: |
        cd frontend
        npm install
        CI=false npm run build
        mkdir -p ../src/main/resources/static/
        cp -r build/* ../src/main/resources/static/

    # 4. Build Spring Boot
    - name: Build Spring Boot
      run: |
        mvn clean package

    # 5. Setup PEM Key
    - name: Setup PEM Key
      run: |
        printf "%s\n" "$KEY_PATH" > private.pem
        chmod 600 private.pem

    # 6. Add EC2 to known_hosts
    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 52.79.138.214 >> ~/.ssh/known_hosts

    # 7. Deploy to EC2
    - name: Deploy to EC2
      env:
        REMOTE_HOST: 52.79.138.214
        REMOTE_USER: ubuntu
        KEY_PATH: ${{ secrets.EC2_KEY }}
      run: |
        scp -o StrictHostKeyChecking=no -i private.pem target/kingsejong-1.0-SNAPSHOT.jar $REMOTE_USER@$REMOTE_HOST:/home/ubuntu/deploy/
        ssh -o StrictHostKeyChecking=no -i private.pem $REMOTE_USER@$REMOTE_HOST "pkill -f java || true && nohup java -jar /home/ubuntu/deploy/kingsejong-1.0-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 &"
