name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 환경 설정
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven

    # 3. React 빌드
    - name: Build React
      run: |
        cd frontend
        npm install
        CI=false npm run build
        mkdir -p ../src/main/resources/static/
        cp -r build/* ../src/main/resources/static/

    # 4. Spring Boot 빌드
    - name: Build Spring Boot
      run: |
        mvn clean package

    # 5. PEM 키 설정 및 검증
    - name: Setup PEM Key
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        printf "%s\n" "$EC2_KEY" > private.pem
        chmod 600 private.pem

    # 6. EC2 호스트를 Known Hosts에 추가
    - name: Add EC2 to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 54.180.244.4 >> ~/.ssh/known_hosts

    # 7. EC2에 JAR 파일 배포 및 실행!
    - name: Deploy to EC2
      env:
        REMOTE_HOST: 54.180.244.4
        REMOTE_USER: ec2-user
      run: |
        scp -o StrictHostKeyChecking=no -i private.pem target/kingsejong-1.0-SNAPSHOT.jar $REMOTE_USER@$REMOTE_HOST:/home/ec2-user/deploy/
        ssh -o StrictHostKeyChecking=no -i private.pem $REMOTE_USER@$REMOTE_HOST "pkill -f java || true && nohup java -jar /home/ec2-user/deploy/kingsejong-1.0-SNAPSHOT.jar > /home/ec2-user/app.log 2>&1 &"
